# Numpy Practice Session

In [1]:
# import libraray
import numpy as np

### Creating array using numpy

In [3]:
food = np.array(["Pakora", "Samosa", "Raita"])
food

array(['Pakora', 'Samosa', 'Raita'], dtype='<U6')

In [5]:
price = np.array([5,5,5])
price

array([5, 5, 5])

In [6]:
type(price)

numpy.ndarray

In [7]:
type(food)

numpy.ndarray

In [8]:
len(price)

3

In [9]:
len(food)

3

In [11]:
price[0:]

array([5, 5, 5])

In [16]:
food[:1]

array(['Pakora'], dtype='<U6')

In [17]:
price.mean()

5.0

In [19]:
# Zeros
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [20]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [21]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [22]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.arange(2,20)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [24]:
np.arange(2,20,3)

array([ 2,  5,  8, 11, 14, 17])

In [25]:
# table
np.arange(0,50,5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [29]:
# line space
np.linspace(0,11, num=7)

array([ 0.        ,  1.83333333,  3.66666667,  5.5       ,  7.33333333,
        9.16666667, 11.        ])

In [30]:
# specify your data type
np.ones(5, dtype=np.int64)

array([1, 1, 1, 1, 1], dtype=int64)

In [32]:
# specify your data type
np.ones(30, dtype=np.float64)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

## array functions

In [36]:
a= np.array([10,13,24,55,0.5,24.5,100])
a

array([ 10. ,  13. ,  24. ,  55. ,   0.5,  24.5, 100. ])

In [38]:
a.sort()
a

array([  0.5,  10. ,  13. ,  24. ,  24.5,  55. , 100. ])

In [39]:
b=np.array([12,16,12.9,83,45.3,8.3])
b

array([12. , 16. , 12.9, 83. , 45.3,  8.3])

In [42]:
c= np.concatenate((a,b))
c

array([  0.5,  10. ,  13. ,  24. ,  24.5,  55. , 100. ,  12. ,  16. ,
        12.9,  83. ,  45.3,   8.3])

In [43]:
c.sort()
c

array([  0.5,   8.3,  10. ,  12. ,  12.9,  13. ,  16. ,  24. ,  24.5,
        45.3,  55. ,  83. , 100. ])

## 2-D array

In [48]:
a= np.array([[1,2],[5,6]])
a

array([[1, 2],
       [5, 6]])

In [46]:
b=np.array([[6,7],[8,9]])
b

array([[6, 7],
       [8, 9]])

In [51]:
c=np.concatenate((a,b), axis=1)
c

array([[1, 2, 6, 7],
       [5, 6, 8, 9]])

In [52]:
d=np.concatenate((a,b), axis=0)
d

array([[1, 2],
       [5, 6],
       [6, 7],
       [8, 9]])

In [53]:
b=np.array([[5,6,7],[1,2,3],[4,5,6]])
b

array([[5, 6, 7],
       [1, 2, 3],
       [4, 5, 6]])

In [54]:
b.ndim

2

In [55]:
# size 9no of elements
b.size

9

In [56]:
#shape
b.shape

(3, 3)

In [57]:
a= np.arange(24)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [59]:
b=a.reshape(3,2,4)
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [60]:
b.ndim

3

In [61]:
#conver 1D to 2D
a= np.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
a.shape

(9,)

In [63]:
b= a[np.newaxis, :]
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [64]:
b.shape

(1, 9)

In [65]:
c= a[:, np.newaxis]
c

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [66]:
c

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [67]:
c[4]

array([5])

In [68]:
c[3:7]

array([[4],
       [5],
       [6],
       [7]])

In [69]:
a[2]

3

In [70]:
a[4:6]

array([5, 6])

In [71]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
a*6

array([ 6, 12, 18, 24, 30, 36, 42, 48, 54])

In [73]:
a+6

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15])

In [74]:
a.sum()

45

In [75]:
a.mean()

5.0

In [76]:
c

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [77]:
c*6

array([[ 6],
       [12],
       [18],
       [24],
       [30],
       [36],
       [42],
       [48],
       [54]])

In [78]:
c+6

array([[ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15]])

In [79]:
c.mean()

5.0

In [80]:
c.sum()

45