In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4,4,5])
a

array([1, 2, 3, 4, 4, 5])

In [7]:
b=np.zeros(3)
b

array([0., 0., 0.])

In [9]:
c=np.ones(4)
c

array([1., 1., 1., 1.])

In [15]:
d=np.empty(2)
d

array([2.28918299e-275, 1.71803325e+266])

In [16]:
e=np.arange(8)
e

array([0, 1, 2, 3, 4, 5, 6, 7])

In [17]:
f=np.arange(2,19)
f

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18])

In [18]:
g=np.arange(1,17,2)
g

array([ 1,  3,  5,  7,  9, 11, 13, 15])

In [23]:
h=np.linspace(1,5,num=5)
h

array([1., 2., 3., 4., 5.])

In [32]:
i=np.ones(5, dtype=np.int64)
i

array([1, 1, 1, 1, 1], dtype=int64)

In [37]:
j=np.ones(5,dtype=np.float32)
j

array([1., 1., 1., 1., 1.], dtype=float32)

In [43]:
k=np.zeros((3,4))
k

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## 3-d array

In [52]:
l=np.arange(36).reshape(4,3,3)
l

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]],

       [[27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])